// Code generated by MockGen. DO NOT EDIT.
// Source: order.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Te8va/Gofermarch/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderServ is a mock of OrderServ interface.
type MockOrderServ struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServMockRecorder
}

// MockOrderServMockRecorder is the mock recorder for MockOrderServ.
type MockOrderServMockRecorder struct {
	mock *MockOrderServ
}

// NewMockOrderServ creates a new mock instance.
func NewMockOrderServ(ctrl *gomock.Controller) *MockOrderServ {
	mock := &MockOrderServ{ctrl: ctrl}
	mock.recorder = &MockOrderServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServ) EXPECT() *MockOrderServMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockOrderServ) GetOrder(ctx context.Context, number string) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, number)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderServMockRecorder) GetOrder(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderServ)(nil).GetOrder), ctx, number)
}

// GetOrdersByUser mocks base method.
func (m *MockOrderServ) GetOrdersByUser(ctx context.Context, login string) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUser", ctx, login)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUser indicates an expected call of GetOrdersByUser.
func (mr *MockOrderServMockRecorder) GetOrdersByUser(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUser", reflect.TypeOf((*MockOrderServ)(nil).GetOrdersByUser), ctx, login)
}

// SaveOrder mocks base method.
func (m *MockOrderServ) SaveOrder(ctx context.Context, order domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderServMockRecorder) SaveOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderServ)(nil).SaveOrder), ctx, order)
}

// UpdateOrder mocks base method.
func (m *MockOrderServ) UpdateOrder(ctx context.Context, number, status string, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderServMockRecorder) UpdateOrder(ctx, number, status, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderServ)(nil).UpdateOrder), ctx, number, status, accrual)
}
