// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Te8va/Gofermarch/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBalanceServ is a mock of BalanceServ interface.
type MockBalanceServ struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServMockRecorder
}

// MockBalanceServMockRecorder is the mock recorder for MockBalanceServ.
type MockBalanceServMockRecorder struct {
	mock *MockBalanceServ
}

// NewMockBalanceServ creates a new mock instance.
func NewMockBalanceServ(ctrl *gomock.Controller) *MockBalanceServ {
	mock := &MockBalanceServ{ctrl: ctrl}
	mock.recorder = &MockBalanceServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceServ) EXPECT() *MockBalanceServMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBalanceServ) GetBalance(ctx context.Context, login string) (domain.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, login)
	ret0, _ := ret[0].(domain.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceServMockRecorder) GetBalance(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceServ)(nil).GetBalance), ctx, login)
}

// GetWithdrawalsByUser mocks base method.
func (m *MockBalanceServ) GetWithdrawalsByUser(ctx context.Context, login string) ([]domain.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUser", ctx, login)
	ret0, _ := ret[0].([]domain.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUser indicates an expected call of GetWithdrawalsByUser.
func (mr *MockBalanceServMockRecorder) GetWithdrawalsByUser(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUser", reflect.TypeOf((*MockBalanceServ)(nil).GetWithdrawalsByUser), ctx, login)
}

// SaveWithdrawal mocks base method.
func (m *MockBalanceServ) SaveWithdrawal(ctx context.Context, w domain.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithdrawal", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWithdrawal indicates an expected call of SaveWithdrawal.
func (mr *MockBalanceServMockRecorder) SaveWithdrawal(ctx, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithdrawal", reflect.TypeOf((*MockBalanceServ)(nil).SaveWithdrawal), ctx, w)
}
